/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f4',
        'surface-dim': '#dcdad5',
        'surface-bright': '#fcf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ee',
        'surface-container': '#f0ede9',
        'surface-container-high': '#ebe8e3',
        'surface-container-highest': '#e5e2dd',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#404944',
        'inverse-surface': '#31302d',
        'inverse-on-surface': '#f3f0eb',
        outline: '#707974',
        'outline-variant': '#bfc9c3',
        'surface-tint': '#306855',
        primary: '#003426',
        'on-primary': '#ffffff',
        'primary-container': '#0f4c3a',
        'on-primary-container': '#82bba4',
        'inverse-primary': '#99d3ba',
        secondary: '#4e6359',
        'on-secondary': '#ffffff',
        'secondary-container': '#d0e8dc',
        'on-secondary-container': '#54695f',
        tertiary: '#610002',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#86120e',
        'on-tertiary-container': '#ff9182',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#b4efd6',
        'primary-fixed-dim': '#99d3ba',
        'on-primary-fixed': '#002117',
        'on-primary-fixed-variant': '#15503e',
        'secondary-fixed': '#d0e8dc',
        'secondary-fixed-dim': '#b5ccc0',
        'on-secondary-fixed': '#0b1f18',
        'on-secondary-fixed-variant': '#364b42',
        'tertiary-fixed': '#ffdad5',
        'tertiary-fixed-dim': '#ffb4aa',
        'on-tertiary-fixed': '#410001',
        'on-tertiary-fixed-variant': '#8c1712',
        background: '#fcf9f4',
        'on-background': '#1c1c19',
        'surface-variant': '#e5e2dd',
        'accent-lime': '#d6ec00',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'container-padding': '20px',
        gutter: '12px',
      },
      fontFamily: {
        headline: ['Lexend', 'sans-serif'],
        display: ['Lexend', 'sans-serif'],
        body: ['"Hanken Grotesk"', 'sans-serif'],
        label: ['"Hanken Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        elevated: '0 4px 12px 0 rgba(0,66,57,0.06)',
        'elevated-top': '0 -4px 12px 0 rgba(0,66,57,0.06)',
        receipt: '0 12px 24px rgba(0, 66, 57, 0.08)',
      },
    },
  },
  plugins: [],
};
